package net.seniorsteps.senior.dal.entity.annotation;
// Generated Jan 6, 2020 9:40:03 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * City generated by hbm2java
 */
@Entity
@Table(name = "city")
public class City implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;

	@Column(name = "name_ar", unique = true, nullable = false, length = 100)
	private String nameAr;

	@Column(name = "name_en", unique = true, nullable = false, length = 100)
	private String nameEn;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "city")
	private Set areas = new HashSet(0);

	public City() {
	}

	public City(String nameAr, String nameEn) {
		this.nameAr = nameAr;
		this.nameEn = nameEn;
	}

	public City(String nameAr, String nameEn, Set areas) {
		this.nameAr = nameAr;
		this.nameEn = nameEn;
		this.areas = areas;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNameAr() {
		return this.nameAr;
	}

	public void setNameAr(String nameAr) {
		this.nameAr = nameAr;
	}

	public String getNameEn() {
		return this.nameEn;
	}

	public void setNameEn(String nameEn) {
		this.nameEn = nameEn;
	}

	public Set getAreas() {
		return this.areas;
	}

	public void setAreas(Set areas) {
		this.areas = areas;
	}

}
