package net.seniorsteps.senior.dal.entity;
// Generated Jan 6, 2020 9:40:03 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Provider generated by hbm2java
 */
@Entity
@Table(name="provider"
    ,catalog="senior_app"
    , uniqueConstraints = {@UniqueConstraint(columnNames="name_ar"), @UniqueConstraint(columnNames="name_en")} 
)
public class Provider  implements java.io.Serializable {


     private Integer id;
     private String nameAr;
     private String nameEn;
     private String hotline;
     private String logoPathAr;
     private String logoPathEn;
     private Set categories = new HashSet(0);
     private Set branches = new HashSet(0);
     private Set providerUsers = new HashSet(0);

    public Provider() {
    }

	
    public Provider(String nameAr, String nameEn) {
        this.nameAr = nameAr;
        this.nameEn = nameEn;
    }
    public Provider(String nameAr, String nameEn, String hotline, String logoPathAr, String logoPathEn, Set categories, Set branches, Set providerUsers) {
       this.nameAr = nameAr;
       this.nameEn = nameEn;
       this.hotline = hotline;
       this.logoPathAr = logoPathAr;
       this.logoPathEn = logoPathEn;
       this.categories = categories;
       this.branches = branches;
       this.providerUsers = providerUsers;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name_ar", unique=true, nullable=false)
    public String getNameAr() {
        return this.nameAr;
    }
    
    public void setNameAr(String nameAr) {
        this.nameAr = nameAr;
    }

    
    @Column(name="name_en", unique=true, nullable=false)
    public String getNameEn() {
        return this.nameEn;
    }
    
    public void setNameEn(String nameEn) {
        this.nameEn = nameEn;
    }

    
    @Column(name="hotline", length=15)
    public String getHotline() {
        return this.hotline;
    }
    
    public void setHotline(String hotline) {
        this.hotline = hotline;
    }

    
    @Column(name="logo_path_ar")
    public String getLogoPathAr() {
        return this.logoPathAr;
    }
    
    public void setLogoPathAr(String logoPathAr) {
        this.logoPathAr = logoPathAr;
    }

    
    @Column(name="logo_path_en")
    public String getLogoPathEn() {
        return this.logoPathEn;
    }
    
    public void setLogoPathEn(String logoPathEn) {
        this.logoPathEn = logoPathEn;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="provider")
    public Set getCategories() {
        return this.categories;
    }
    
    public void setCategories(Set categories) {
        this.categories = categories;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="provider")
    public Set getBranches() {
        return this.branches;
    }
    
    public void setBranches(Set branches) {
        this.branches = branches;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="provider")
    public Set getProviderUsers() {
        return this.providerUsers;
    }
    
    public void setProviderUsers(Set providerUsers) {
        this.providerUsers = providerUsers;
    }




}


